name: build

on:
  push:
    branches: [ master, develop ]
  pull_request:
    branches: [ master, develop ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: make
      run: make NOREADLINE=1
    - name: make tests
      run: |
           sudo mkdir /etc/ccalc
           sudo cp simplification.ruleset /etc/ccalc
           make tests
